# Use root/example as user/password credentials
version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mymongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  web:
    build: .
    command: "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ".:/src/."
