# Use root/example as user/password credentials
version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    container_name: mymongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    env_file:
      - ./mongodb.env
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    restart: always
    container_name: MY_MONGO_EXPRESS
    ports:
      - "8001:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mymongodb:27017/
      ME_CONFIG_BASICAUTH: false
    env_file:
      - ./mongo-express.env
    networks:
      - mynetwork

  web:
    build: .
    command: "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ".:/src/."
    networks:
      - mynetwork
    depends_on:
      - mongo
